title: Richard Bryan Whitmire # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 This is my personal portfolio of data analytics projects that I have created.
  <br><br>
  <a href="www.linkedin.com/in/bryan-whitmire">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
